name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # 每天凌晨自动更新
  workflow_dispatch: # 支持手动触发
  push:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: WavesMan
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Shanghai # 设置时区
          # 常用插件（可以按需开启）
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_activity: no
