name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # 每天凌晨自动更新
  workflow_dispatch: # 支持手动触发
  push:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 20
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: WavesMan
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Shanghai # 设置时区
          # 常用插件（可以按需开启）
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_activity: no
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
          plugin_habits_days: 14
          plugin_habits_from: 300
          config_order: base.header, isocalendar, languages, habits, base.repositories, base.community, base.metadata
